<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Material;

class CoffeeMaterialSeeder extends Seeder
{
    public function run(): void
    {
        $materials = [
            // ─── Beans & Coffee ───────────────────────────────────────
            [
                'name'                      => 'Espresso Beans',
                'code'                      => 'MAT-COFFEE-001',
                'quantity_in_stock'         => 50,
                'current_quantity_material' => 50,
                'unit'                      => 'g',
                'category_id'               => 1,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Arabica Beans',
                'code'                      => 'MAT-COFFEE-002',
                'quantity_in_stock'         => 40,
                'current_quantity_material' => 40,
                'unit'                      => 'g',
                'category_id'               => 1,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Robusta Beans',
                'code'                      => 'MAT-COFFEE-003',
                'quantity_in_stock'         => 5,
                'current_quantity_material' => 5,
                'unit'                      => 'g',
                'category_id'               => 1,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Decaf Coffee Beans',
                'code'                      => 'MAT-COFFEE-004',
                'quantity_in_stock'         => 0,
                'current_quantity_material' => 0,
                'unit'                      => 'g',
                'category_id'               => 1,
                'image'                     => null,
                'status'                    => 'out_of_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Cold Brew Concentrate',
                'code'                      => 'MAT-COFFEE-005',
                'quantity_in_stock'         => 20,
                'current_quantity_material' => 20,
                'unit'                      => 'l',
                'category_id'               => 1,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'internal',
            ],
            [
                'name'                      => 'Instant Coffee Powder',
                'code'                      => 'MAT-COFFEE-006',
                'quantity_in_stock'         => 3,
                'current_quantity_material' => 3,
                'unit'                      => 'g',
                'category_id'               => 1,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],

            // ─── Milk & Dairy ─────────────────────────────────────────
            [
                'name'                      => 'Whole Milk',
                'code'                      => 'MAT-DAIRY-001',
                'quantity_in_stock'         => 100,
                'current_quantity_material' => 100,
                'unit'                      => 'l',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Skimmed Milk',
                'code'                      => 'MAT-DAIRY-002',
                'quantity_in_stock'         => 60,
                'current_quantity_material' => 60,
                'unit'                      => 'l',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Oat Milk',
                'code'                      => 'MAT-DAIRY-003',
                'quantity_in_stock'         => 4,
                'current_quantity_material' => 4,
                'unit'                      => 'l',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Almond Milk',
                'code'                      => 'MAT-DAIRY-004',
                'quantity_in_stock'         => 0,
                'current_quantity_material' => 0,
                'unit'                      => 'l',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'out_of_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Soy Milk',
                'code'                      => 'MAT-DAIRY-005',
                'quantity_in_stock'         => 30,
                'current_quantity_material' => 30,
                'unit'                      => 'l',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Whipped Cream',
                'code'                      => 'MAT-DAIRY-006',
                'quantity_in_stock'         => 40,
                'current_quantity_material' => 40,
                'unit'                      => 'l',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'internal',
            ],
            [
                'name'                      => 'Condensed Milk',
                'code'                      => 'MAT-DAIRY-007',
                'quantity_in_stock'         => 6,
                'current_quantity_material' => 6,
                'unit'                      => 'g',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Coconut Milk',
                'code'                      => 'MAT-DAIRY-008',
                'quantity_in_stock'         => 25,
                'current_quantity_material' => 25,
                'unit'                      => 'l',
                'category_id'               => 2,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],

            // ─── Syrups & Sweeteners ──────────────────────────────────
            [
                'name'                      => 'White Sugar',
                'code'                      => 'MAT-SWT-001',
                'quantity_in_stock'         => 30,
                'current_quantity_material' => 30,
                'unit'                      => 'g',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Brown Sugar',
                'code'                      => 'MAT-SWT-002',
                'quantity_in_stock'         => 3,
                'current_quantity_material' => 3,
                'unit'                      => 'g',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Vanilla Syrup',
                'code'                      => 'MAT-SWT-003',
                'quantity_in_stock'         => 20,
                'current_quantity_material' => 20,
                'unit'                      => 'l',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'internal',
            ],
            [
                'name'                      => 'Caramel Sauce',
                'code'                      => 'MAT-SWT-004',
                'quantity_in_stock'         => 15,
                'current_quantity_material' => 15,
                'unit'                      => 'l',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'internal',
            ],
            [
                'name'                      => 'Hazelnut Syrup',
                'code'                      => 'MAT-SWT-005',
                'quantity_in_stock'         => 0,
                'current_quantity_material' => 0,
                'unit'                      => 'l',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'out_of_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Lavender Syrup',
                'code'                      => 'MAT-SWT-006',
                'quantity_in_stock'         => 10,
                'current_quantity_material' => 10,
                'unit'                      => 'l',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'internal',
            ],
            [
                'name'                      => 'Honey',
                'code'                      => 'MAT-SWT-007',
                'quantity_in_stock'         => 4,
                'current_quantity_material' => 4,
                'unit'                      => 'g',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Stevia Powder',
                'code'                      => 'MAT-SWT-008',
                'quantity_in_stock'         => 8,
                'current_quantity_material' => 8,
                'unit'                      => 'g',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Rose Syrup',
                'code'                      => 'MAT-SWT-009',
                'quantity_in_stock'         => 0,
                'current_quantity_material' => 0,
                'unit'                      => 'l',
                'category_id'               => 3,
                'image'                     => null,
                'status'                    => 'out_of_stock',
                'material_type'             => 'internal',
            ],

            // ─── Powders & Toppings ───────────────────────────────────
            [
                'name'                      => 'Chocolate Powder',
                'code'                      => 'MAT-PWD-001',
                'quantity_in_stock'         => 25,
                'current_quantity_material' => 25,
                'unit'                      => 'g',
                'category_id'               => 4,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Matcha Powder',
                'code'                      => 'MAT-PWD-002',
                'quantity_in_stock'         => 3,
                'current_quantity_material' => 3,
                'unit'                      => 'g',
                'category_id'               => 4,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Cinnamon Powder',
                'code'                      => 'MAT-PWD-003',
                'quantity_in_stock'         => 10,
                'current_quantity_material' => 10,
                'unit'                      => 'g',
                'category_id'               => 4,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Turmeric Powder',
                'code'                      => 'MAT-PWD-004',
                'quantity_in_stock'         => 0,
                'current_quantity_material' => 0,
                'unit'                      => 'g',
                'category_id'               => 4,
                'image'                     => null,
                'status'                    => 'out_of_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Cocoa Nibs',
                'code'                      => 'MAT-PWD-005',
                'quantity_in_stock'         => 12,
                'current_quantity_material' => 12,
                'unit'                      => 'g',
                'category_id'               => 4,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Nutmeg Powder',
                'code'                      => 'MAT-PWD-006',
                'quantity_in_stock'         => 2,
                'current_quantity_material' => 2,
                'unit'                      => 'g',
                'category_id'               => 4,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],

            // ─── Packaging ────────────────────────────────────────────
            [
                'name'                      => 'Paper Cup (8oz)',
                'code'                      => 'MAT-Pg-001',
                'quantity_in_stock'         => 1200,
                'current_quantity_material' => 1200,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Paper Cup (12oz)',
                'code'                      => 'MAT-Pg-002',
                'quantity_in_stock'         => 1000,
                'current_quantity_material' => 1000,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Paper Cup (16oz)',
                'code'                      => 'MAT-Pg-003',
                'quantity_in_stock'         => 800,
                'current_quantity_material' => 800,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Plastic Cold Cup (16oz)',
                'code'                      => 'MAT-Pg-004',
                'quantity_in_stock'         => 50,
                'current_quantity_material' => 50,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Cup Lids',
                'code'                      => 'MAT-Pg-005',
                'quantity_in_stock'         => 2000,
                'current_quantity_material' => 2000,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Paper Straws',
                'code'                      => 'MAT-Pg-006',
                'quantity_in_stock'         => 0,
                'current_quantity_material' => 0,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'out_of_stock',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Cup Sleeves',
                'code'                      => 'MAT-Pg-007',
                'quantity_in_stock'         => 500,
                'current_quantity_material' => 500,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'good',
                'material_type'             => 'external',
            ],
            [
                'name'                      => 'Kraft Paper Bags',
                'code'                      => 'MAT-Pg-008',
                'quantity_in_stock'         => 4,
                'current_quantity_material' => 4,
                'unit'                      => 'g',
                'category_id'               => 5,
                'image'                     => null,
                'status'                    => 'low_stock',
                'material_type'             => 'external',
            ],
        ];

        foreach ($materials as $material) {
            Material::updateOrCreate(
                ['code' => $material['code']],
                $material
            );
        }
    }
}