<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GovernorateAndCitySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('cities')->truncate();
        DB::table('governorates')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Governorate: name, code (plate number zero-padded)
        $governorates = [
            ['id' => 1,  'name' => 'Adana',          'code' => '01'],
            ['id' => 2,  'name' => 'Adıyaman',        'code' => '02'],
            ['id' => 3,  'name' => 'Afyonkarahisar',  'code' => '03'],
            ['id' => 4,  'name' => 'Ağrı',            'code' => '04'],
            ['id' => 5,  'name' => 'Amasya',          'code' => '05'],
            ['id' => 6,  'name' => 'Ankara',          'code' => '06'],
            ['id' => 7,  'name' => 'Antalya',         'code' => '07'],
            ['id' => 8,  'name' => 'Artvin',          'code' => '08'],
            ['id' => 9,  'name' => 'Aydın',           'code' => '09'],
            ['id' => 10, 'name' => 'Balıkesir',       'code' => '10'],
            ['id' => 11, 'name' => 'Bilecik',         'code' => '11'],
            ['id' => 12, 'name' => 'Bingöl',          'code' => '12'],
            ['id' => 13, 'name' => 'Bitlis',          'code' => '13'],
            ['id' => 14, 'name' => 'Bolu',            'code' => '14'],
            ['id' => 15, 'name' => 'Burdur',          'code' => '15'],
            ['id' => 16, 'name' => 'Bursa',           'code' => '16'],
            ['id' => 17, 'name' => 'Çanakkale',       'code' => '17'],
            ['id' => 18, 'name' => 'Çankırı',         'code' => '18'],
            ['id' => 19, 'name' => 'Çorum',           'code' => '19'],
            ['id' => 20, 'name' => 'Denizli',         'code' => '20'],
            ['id' => 21, 'name' => 'Diyarbakır',      'code' => '21'],
            ['id' => 22, 'name' => 'Edirne',          'code' => '22'],
            ['id' => 23, 'name' => 'Elazığ',          'code' => '23'],
            ['id' => 24, 'name' => 'Erzincan',        'code' => '24'],
            ['id' => 25, 'name' => 'Erzurum',         'code' => '25'],
            ['id' => 26, 'name' => 'Eskişehir',       'code' => '26'],
            ['id' => 27, 'name' => 'Gaziantep',       'code' => '27'],
            ['id' => 28, 'name' => 'Giresun',         'code' => '28'],
            ['id' => 29, 'name' => 'Gümüşhane',       'code' => '29'],
            ['id' => 30, 'name' => 'Hakkâri',         'code' => '30'],
            ['id' => 31, 'name' => 'Hatay',           'code' => '31'],
            ['id' => 32, 'name' => 'Isparta',         'code' => '32'],
            ['id' => 33, 'name' => 'Mersin',          'code' => '33'],
            ['id' => 34, 'name' => 'İstanbul',        'code' => '34'],
            ['id' => 35, 'name' => 'İzmir',           'code' => '35'],
            ['id' => 36, 'name' => 'Kars',            'code' => '36'],
            ['id' => 37, 'name' => 'Kastamonu',       'code' => '37'],
            ['id' => 38, 'name' => 'Kayseri',         'code' => '38'],
            ['id' => 39, 'name' => 'Kırklareli',      'code' => '39'],
            ['id' => 40, 'name' => 'Kırşehir',        'code' => '40'],
            ['id' => 41, 'name' => 'Kocaeli',         'code' => '41'],
            ['id' => 42, 'name' => 'Konya',           'code' => '42'],
            ['id' => 43, 'name' => 'Kütahya',         'code' => '43'],
            ['id' => 44, 'name' => 'Malatya',         'code' => '44'],
            ['id' => 45, 'name' => 'Manisa',          'code' => '45'],
            ['id' => 46, 'name' => 'Kahramanmaraş',   'code' => '46'],
            ['id' => 47, 'name' => 'Mardin',          'code' => '47'],
            ['id' => 48, 'name' => 'Muğla',           'code' => '48'],
            ['id' => 49, 'name' => 'Muş',             'code' => '49'],
            ['id' => 50, 'name' => 'Nevşehir',        'code' => '50'],
            ['id' => 51, 'name' => 'Niğde',           'code' => '51'],
            ['id' => 52, 'name' => 'Ordu',            'code' => '52'],
            ['id' => 53, 'name' => 'Rize',            'code' => '53'],
            ['id' => 54, 'name' => 'Sakarya',         'code' => '54'],
            ['id' => 55, 'name' => 'Samsun',          'code' => '55'],
            ['id' => 56, 'name' => 'Siirt',           'code' => '56'],
            ['id' => 57, 'name' => 'Sinop',           'code' => '57'],
            ['id' => 58, 'name' => 'Sivas',           'code' => '58'],
            ['id' => 59, 'name' => 'Tekirdağ',        'code' => '59'],
            ['id' => 60, 'name' => 'Tokat',           'code' => '60'],
            ['id' => 61, 'name' => 'Trabzon',         'code' => '61'],
            ['id' => 62, 'name' => 'Tunceli',         'code' => '62'],
            ['id' => 63, 'name' => 'Şanlıurfa',       'code' => '63'],
            ['id' => 64, 'name' => 'Uşak',            'code' => '64'],
            ['id' => 65, 'name' => 'Van',             'code' => '65'],
            ['id' => 66, 'name' => 'Yozgat',          'code' => '66'],
            ['id' => 67, 'name' => 'Zonguldak',       'code' => '67'],
            ['id' => 68, 'name' => 'Aksaray',         'code' => '68'],
            ['id' => 69, 'name' => 'Bayburt',         'code' => '69'],
            ['id' => 70, 'name' => 'Karaman',         'code' => '70'],
            ['id' => 71, 'name' => 'Kırıkkale',       'code' => '71'],
            ['id' => 72, 'name' => 'Batman',          'code' => '72'],
            ['id' => 73, 'name' => 'Şırnak',          'code' => '73'],
            ['id' => 74, 'name' => 'Bartın',          'code' => '74'],
            ['id' => 75, 'name' => 'Ardahan',         'code' => '75'],
            ['id' => 76, 'name' => 'Iğdır',           'code' => '76'],
            ['id' => 77, 'name' => 'Yalova',          'code' => '77'],
            ['id' => 78, 'name' => 'Karabük',         'code' => '78'],
            ['id' => 79, 'name' => 'Kilis',           'code' => '79'],
            ['id' => 80, 'name' => 'Osmaniye',        'code' => '80'],
            ['id' => 81, 'name' => 'Düzce',           'code' => '81'],
        ];

        DB::table('governorates')->insert($governorates);

        // Province-centre coordinates (reused per district within that province)
        $plateCentroids = [
            1  => [37.0000, 35.3213], 2  => [37.7648, 38.2786], 3  => [38.7638, 30.5403],
            4  => [39.7191, 43.0506], 5  => [40.6565, 35.8374], 6  => [39.9334, 32.8597],
            7  => [36.8969, 30.7133], 8  => [41.1828, 41.8183], 9  => [37.8444, 27.8458],
            10 => [39.6484, 27.8826], 11 => [40.1501, 29.9833], 12 => [38.8847, 40.4982],
            13 => [38.4016, 42.1083], 14 => [40.7339, 31.6061], 15 => [37.7206, 30.2909],
            16 => [40.1826, 29.0665], 17 => [40.1553, 26.4142], 18 => [40.6013, 33.6134],
            19 => [40.5506, 34.9556], 20 => [37.7765, 29.0864], 21 => [37.9144, 40.2306],
            22 => [41.6772, 26.5556], 23 => [38.6748, 39.2226], 24 => [39.7500, 39.5000],
            25 => [39.9000, 41.2700], 26 => [39.7767, 30.5206], 27 => [37.0662, 37.3833],
            28 => [40.9128, 38.3895], 29 => [40.4603, 39.4814], 30 => [37.5744, 43.7408],
            31 => [36.4018, 36.3498], 32 => [37.7648, 30.5566], 33 => [36.8121, 34.6415],
            34 => [41.0082, 28.9784], 35 => [38.4237, 27.1428], 36 => [40.6013, 43.0975],
            37 => [41.3766, 33.7765], 38 => [38.7312, 35.4787], 39 => [41.7333, 27.2253],
            40 => [39.1425, 34.1709], 41 => [40.8533, 29.8815], 42 => [37.8667, 32.4833],
            43 => [39.4167, 29.9833], 44 => [38.3552, 38.3095], 45 => [38.6191, 27.4289],
            46 => [37.5858, 36.9371], 47 => [37.3212, 40.7245], 48 => [37.2153, 28.3636],
            49 => [38.9462, 41.7539], 50 => [38.6939, 34.6857], 51 => [37.9667, 34.6833],
            52 => [40.9839, 37.8764], 53 => [41.0201, 40.5234], 54 => [40.7569, 30.3783],
            55 => [41.2867, 36.3300], 56 => [37.9333, 42.0167], 57 => [42.0231, 35.1531],
            58 => [39.7477, 37.0179], 59 => [40.9833, 27.5167], 60 => [40.3167, 36.5544],
            61 => [41.0015, 39.7178], 62 => [39.3074, 39.4388], 63 => [37.1591, 38.7969],
            64 => [38.6823, 29.4082], 65 => [38.4891, 43.4089], 66 => [39.8181, 34.8147],
            67 => [41.4564, 31.7987], 68 => [38.3687, 34.0370], 69 => [40.2552, 40.2249],
            70 => [37.1759, 33.2287], 71 => [39.8468, 33.5153], 72 => [37.8812, 41.1351],
            73 => [37.5164, 42.4610], 74 => [41.5811, 32.4610], 75 => [41.1105, 42.7022],
            76 => [39.9237, 44.0450], 77 => [40.6550, 29.2769], 78 => [41.2061, 32.6204],
            79 => [36.7184, 37.1212], 80 => [37.0742, 36.2464], 81 => [40.8438, 31.1565],
        ];

        // Districts per province
        $districts = [
            1  => ['Aladağ','Ceyhan','Çukurova','Feke','İmamoğlu','Karaisalı','Karataş','Kozan','Pozantı','Saimbeyli','Sarıçam','Seyhan','Tufanbeyli','Yumurtalık','Yüreğir'],
            2  => ['Besni','Çelikhan','Gerger','Gölbaşı','Kahta','Merkez','Samsat','Sincik','Tut'],
            3  => ['Başmakçı','Bayat','Bolvadin','Çay','Çobanlar','Dazkırı','Dinar','Emirdağ','Evciler','Hocalar','İhsaniye','İscehisar','Kızılören','Merkez','Sandıklı','Sinanpaşa','Sultandağı','Şuhut'],
            4  => ['Diyadin','Doğubayazıt','Eleşkirt','Hamur','Merkez','Patnos','Taşlıçay','Tutak'],
            5  => ['Göynücek','Gümüşhacıköy','Hamamözü','Merkez','Merzifon','Suluova','Taşova'],
            6  => ['Altındağ','Ayaş','Balâ','Beypazarı','Çamlıdere','Çankaya','Çubuk','Elmadağ','Etimesgut','Evren','Gölbaşı','Güdül','Haymana','Kalecik','Kahramankazan','Keçiören','Kızılcahamam','Mamak','Nallıhan','Polatlı','Pursaklar','Sincan','Şereflikoçhisar','Yenimahalle'],
            7  => ['Akseki','Aksu','Alanya','Demre','Döşemealtı','Elmalı','Finike','Gazipaşa','Gündoğmuş','İbradı','Kaş','Kemer','Kepez','Konyaaltı','Korkuteli','Kumluca','Manavgat','Muratpaşa','Serik'],
            8  => ['Ardanuç','Arhavi','Borçka','Hopa','Kemalpaşa','Merkez','Murgul','Şavşat','Yusufeli'],
            9  => ['Bozdoğan','Buharkent','Çine','Didim','Efeler','Germencik','İncirliova','Karacasu','Karpuzlu','Koçarlı','Köşk','Kuşadası','Kuyucak','Nazilli','Söke','Sultanhisar','Yenipazar'],
            10 => ['Altıeylül','Ayvalık','Balya','Bandırma','Bigadiç','Burhaniye','Dursunbey','Edremit','Erdek','Gömeç','Gönen','Havran','İvrindi','Karesi','Kepsut','Manyas','Marmara','Savaştepe','Sındırgı','Susurluk'],
            11 => ['Bozüyük','Gölpazarı','İnhisar','Merkez','Osmaneli','Pazaryeri','Söğüt','Yenipazar'],
            12 => ['Adaklı','Genç','Karlıova','Kiğı','Merkez','Solhan','Yayladere','Yedisu'],
            13 => ['Adilcevaz','Ahlat','Güroymak','Hizan','Merkez','Mutki','Tatvan'],
            14 => ['Dörtdivan','Gerede','Göynük','Kıbrıscık','Mengen','Merkez','Mudurnu','Seben','Yeniçağa'],
            15 => ['Ağlasun','Altınyayla','Bucak','Çavdır','Çeltikçi','Gölhisar','Karamanlı','Kemer','Merkez','Tefenni','Yeşilova'],
            16 => ['Büyükorhan','Gemlik','Gürsu','Harmancık','İnegöl','İznik','Karacabey','Keles','Kestel','Mudanya','Mustafakemalpaşa','Nilüfer','Orhaneli','Orhangazi','Osmangazi','Yenişehir','Yıldırım'],
            17 => ['Ayvacık','Bayramiç','Biga','Bozcaada','Çan','Eceabat','Ezine','Gelibolu','Gökçeada','Lapseki','Merkez','Yenice'],
            18 => ['Atkaracalar','Bayramören','Çerkeş','Eldivan','Ilgaz','Kızılırmak','Korgun','Kurşunlu','Merkez','Orta','Şabanözü','Yapraklı'],
            19 => ['Alaca','Bayat','Boğazkale','Dodurga','İskilip','Kargı','Laçin','Mecitözü','Merkez','Oğuzlar','Ortaköy','Osmancık','Sungurlu','Uğurludağ'],
            20 => ['Acıpayam','Babadağ','Baklan','Bekilli','Beyağaç','Bozkurt','Buldan','Çal','Çameli','Çardak','Çivril','Güney','Honaz','Kale','Merkezefendi','Pamukkale','Sarayköy','Serinhisar','Tavas'],
            21 => ['Bağlar','Bismil','Çermik','Çınar','Çüngüş','Dicle','Eğil','Ergani','Hani','Hazro','Kayapınar','Kocaköy','Kulp','Lice','Silvan','Sur','Yenişehir'],
            22 => ['Enez','Havsa','İpsala','Keşan','Lalapaşa','Meriç','Merkez','Süloğlu','Uzunköprü'],
            23 => ['Ağın','Alacakaya','Arıcak','Baskil','Karakoçan','Keban','Kovancılar','Maden','Merkez','Palu','Sivrice'],
            24 => ['Çayırlı','İliç','Kemah','Kemaliye','Merkez','Otlukbeli','Refahiye','Tercan','Üzümlü'],
            25 => ['Aşkale','Aziziye','Çat','Hınıs','Horasan','İspir','Karaçoban','Karayazı','Köprüköy','Narman','Oltu','Olur','Palandöken','Pasinler','Pazaryolu','Şenkaya','Tekman','Tortum','Uzundere','Yakutiye'],
            26 => ['Alpu','Beylikova','Çifteler','Günyüzü','Han','İnönü','Mahmudiye','Mihalgazi','Mihalıççık','Odunpazarı','Sarıcakaya','Seyitgazi','Sivrihisar','Tepebaşı'],
            27 => ['Araban','İslahiye','Karkamış','Nizip','Nurdağı','Oğuzeli','Şahinbey','Şehitkamil','Yavuzeli'],
            28 => ['Alucra','Bulancak','Çamoluk','Çanakçı','Dereli','Doğankent','Espiye','Eynesil','Görele','Güce','Keşap','Merkez','Piraziz','Şebinkarahisar','Tirebolu','Yağlıdere'],
            29 => ['Kelkit','Köse','Kürtün','Merkez','Şiran','Torul'],
            30 => ['Çukurca','Derecik','Merkez','Şemdinli','Yüksekova'],
            31 => ['Altınözü','Antakya','Arsuz','Belen','Defne','Dörtyol','Erzin','Hassa','İskenderun','Kırıkhan','Kumlu','Payas','Reyhanlı','Samandağ','Yayladağı'],
            32 => ['Aksu','Atabey','Eğirdir','Gelendost','Gönen','Keçiborlu','Merkez','Senirkent','Sütçüler','Şarkikaraağaç','Uluborlu','Yalvaç','Yenişarbademli'],
            33 => ['Akdeniz','Anamur','Aydıncık','Bozyazı','Çamlıyayla','Erdemli','Gülnar','Mezitli','Mut','Silifke','Tarsus','Toroslar','Yenişehir'],
            34 => ['Adalar','Arnavutköy','Ataşehir','Avcılar','Bağcılar','Bahçelievler','Bakırköy','Başakşehir','Bayrampaşa','Beşiktaş','Beykoz','Beylikdüzü','Beyoğlu','Büyükçekmece','Çatalca','Çekmeköy','Esenler','Esenyurt','Eyüpsultan','Fatih','Gaziosmanpaşa','Güngören','Kadıköy','Kağıthane','Kartal','Küçükçekmece','Maltepe','Pendik','Sancaktepe','Sarıyer','Silivri','Sultanbeyli','Sultangazi','Şile','Şişli','Tuzla','Ümraniye','Üsküdar','Zeytinburnu'],
            35 => ['Aliağa','Balçova','Bayındır','Bayraklı','Bergama','Beydağ','Bornova','Buca','Çeşme','Çiğli','Dikili','Foça','Gaziemir','Güzelbahçe','Karabağlar','Karaburun','Karşıyaka','Kemalpaşa','Kınık','Kiraz','Konak','Menderes','Menemen','Narlıdere','Ödemiş','Seferihisar','Selçuk','Tire','Torbalı','Urla'],
            36 => ['Akyaka','Arpaçay','Digor','Kağızman','Merkez','Sarıkamış','Selim','Susuz'],
            37 => ['Abana','Ağlı','Araç','Azdavay','Bozkurt','Cide','Çatalzeytin','Daday','Devrekani','Doğanyurt','Hanönü','İhsangazi','İnebolu','Küre','Merkez','Pınarbaşı','Seydiler','Şenpazar','Taşköprü','Tosya'],
            38 => ['Akkışla','Bünyan','Develi','Felahiye','Hacılar','İncesu','Kocasinan','Melikgazi','Özvatan','Pınarbaşı','Sarıoğlan','Sarız','Talas','Tomarza','Yahyalı','Yeşilhisar'],
            39 => ['Babaeski','Demirköy','Kofçaz','Lüleburgaz','Merkez','Pehlivanköy','Pınarhisar','Vize'],
            40 => ['Akçakent','Akpınar','Boztepe','Çiçekdağı','Kaman','Merkez','Mucur'],
            41 => ['Başiskele','Çayırova','Darıca','Derince','Dilovası','Gebze','Gölcük','İzmit','Kandıra','Karamürsel','Kartepe','Körfez'],
            42 => ['Ahırlı','Akören','Akşehir','Altınekin','Beyşehir','Bozkır','Cihanbeyli','Çeltik','Çumra','Derbent','Derebucak','Doğanhisar','Emirgazi','Ereğli','Güneysınır','Hadim','Halkapınar','Hüyük','Ilgın','Kadınhanı','Karapınar','Karatay','Kulu','Meram','Sarayönü','Selçuklu','Seydişehir','Taşkent','Tuzlukçu','Yalıhüyük','Yunak'],
            43 => ['Altıntaş','Aslanapa','Çavdarhisar','Domaniç','Dumlupınar','Emet','Gediz','Hisarcık','Merkez','Pazarlar','Şaphane','Simav','Tavşanlı'],
            44 => ['Akçadağ','Arapgir','Arguvan','Battalgazi','Darende','Doğanşehir','Doğanyol','Hekimhan','Kale','Kuluncak','Pütürge','Yazıhan','Yeşilyurt'],
            45 => ['Ahmetli','Akhisar','Alaşehir','Demirci','Gölmarmara','Gördes','Kırkağaç','Köprübaşı','Kula','Salihli','Sarıgöl','Saruhanlı','Selendi','Soma','Şehzadeler','Turgutlu','Yunusemre'],
            46 => ['Afşin','Andırın','Çağlayancerit','Dulkadiroğlu','Ekinözü','Elbistan','Göksun','Nurhak','Onikişubat','Pazarcık','Türkoğlu'],
            47 => ['Artuklu','Dargeçit','Derik','Kızıltepe','Mazıdağı','Midyat','Nusaybin','Ömerli','Savur','Yeşilli'],
            48 => ['Bodrum','Dalaman','Datça','Fethiye','Kavaklıdere','Köyceğiz','Marmaris','Menteşe','Milas','Ortaca','Seydikemer','Ula','Yatağan'],
            49 => ['Bulanık','Hasköy','Korkut','Malazgirt','Merkez','Varto'],
            50 => ['Acıgöl','Avanos','Derinkuyu','Gülşehir','Hacıbektaş','Kozaklı','Merkez','Ürgüp'],
            51 => ['Altunhisar','Bor','Çamardı','Çiftlik','Merkez','Ulukışla'],
            52 => ['Akkuş','Altınordu','Aybastı','Çamaş','Çatalpınar','Çaybaşı','Fatsa','Gölköy','Gülyalı','Gürgentepe','İkizce','Kabadüz','Kabataş','Korgan','Kumru','Mesudiye','Perşembe','Ulubey','Ünye'],
            53 => ['Ardeşen','Çamlıhemşin','Çayeli','Derepazarı','Fındıklı','Güneysu','Hemşin','İkizdere','İyidere','Kalkandere','Merkez','Pazar'],
            54 => ['Adapazarı','Akyazı','Arifiye','Erenler','Ferizli','Geyve','Hendek','Karapürçek','Karasu','Kaynarca','Kocaali','Mithatpaşa','Pamukova','Sapanca','Serdivan','Söğütlü','Taraklı'],
            55 => ['Alaçam','Asarcık','Atakum','Ayvacık','Bafra','Canik','Çarşamba','Havza','İlkadım','Kavak','Ladik','Ondokuzmayıs','Salıpazarı','Tekkeköy','Terme','Vezirköprü','Yakakent'],
            56 => ['Baykan','Eruh','Kurtalan','Merkez','Pervari','Şirvan','Tillo'],
            57 => ['Ayancık','Boyabat','Dikmen','Durağan','Erfelek','Gerze','Merkez','Saraydüzü','Türkeli'],
            58 => ['Akıncılar','Altınyayla','Divriği','Doğanşar','Gemerek','Gölova','Hafik','İmranlı','Kangal','Koyulhisar','Merkez','Şarkışla','Suşehri','Ulaş','Yıldızeli','Zara'],
            59 => ['Çerkezköy','Çorlu','Ergene','Hayrabolu','Kapaklı','Malkara','Marmaraereğlisi','Muratlı','Saray','Süleymanpaşa','Şarköy'],
            60 => ['Almus','Artova','Başçiftlik','Erbaa','Merkez','Niksar','Pazar','Reşadiye','Sulusaray','Turhal','Yeşilyurt','Zile'],
            61 => ['Akçaabat','Araklı','Arsin','Beşikdüzü','Çarşıbaşı','Çaykara','Dernekpazarı','Düzköy','Hayrat','Köprübaşı','Maçka','Merkez','Of','Ortahisar','Sürmene','Şalpazarı','Tonya','Vakfıkebir','Yomra'],
            62 => ['Çemişgezek','Hozat','Mazgirt','Merkez','Nazımiye','Ovacık','Pertek','Pülümür'],
            63 => ['Akçakale','Birecik','Bozova','Ceylanpınar','Eyyübiye','Halfeti','Haliliye','Harran','Hilvan','Karaköprü','Siverek','Suruç','Viranşehir'],
            64 => ['Banaz','Eşme','Karahallı','Merkez','Sivaslı','Ulubey'],
            65 => ['Bahçesaray','Başkale','Çaldıran','Çatak','Edremit','Erciş','Gevaş','Gürpınar','İpekyolu','Muradiye','Özalp','Saray','Tuşba'],
            66 => ['Akdağmadeni','Aydıncık','Boğazlıyan','Çandır','Çayıralan','Çekerek','Kadışehri','Merkez','Saraykent','Sarıkaya','Şefaatli','Sorgun','Yenifakılı','Yerköy'],
            67 => ['Alapli','Çaycuma','Devrek','Ereğli','Gökçebey','Kilimli','Kozlu','Merkez'],
            68 => ['Ağaçören','Eskil','Gülağaç','Güzelyurt','Merkez','Ortaköy','Sarıyahşi','Sultanhanı'],
            69 => ['Aydıntepe','Demirözü','Merkez'],
            70 => ['Ayrancı','Başyayla','Ermenek','Kazımkarabekir','Merkez','Sarıveliler'],
            71 => ['Bahşili','Balışeyh','Çelebi','Delice','Karakeçili','Keskin','Merkez','Sulakyurt','Yahşihan'],
            72 => ['Beşiri','Gercüş','Hasankeyf','Kozluk','Merkez','Sason'],
            73 => ['Beytüşşebap','Cizre','Güçlükonak','İdil','Merkez','Silopi','Uludere'],
            74 => ['Amasra','Kurucaşile','Merkez','Ulus'],
            75 => ['Çıldır','Damal','Göle','Hanak','Merkez','Posof'],
            76 => ['Aralık','Karakoyunlu','Merkez','Tuzluca'],
            77 => ['Altınova','Armutlu','Çınarcık','Çiftlikköy','Merkez','Termal'],
            78 => ['Eflani','Eskipazar','Merkez','Ovacık','Safranbolu','Yenice'],
            79 => ['Elbeyli','Merkez','Musabeyli','Polateli'],
            80 => ['Bahçe','Düziçi','Hasanbeyli','Kadirli','Merkez','Sumbas','Toprakkale'],
            81 => ['Akçakoca','Cumayeri','Çilimli','Gölyaka','Gümüşova','Kaynaşlı','Merkez','Yığılca'],
        ];

        $cities = [];
        foreach ($districts as $govId => $names) {
            [$lat, $lng] = $plateCentroids[$govId];
            $plate = str_pad($govId, 2, '0', STR_PAD_LEFT);
            foreach ($names as $index => $name) {
                $cities[] = [
                    'name'           => $name,
                    'latitude'       => $lat,
                    'longitude'      => $lng,
                    'is_active'      => true,
                    // e.g. 01001, 01002 … 34039
                    'code'           => $plate . str_pad($index + 1, 3, '0', STR_PAD_LEFT),
                    'governorate_id' => $govId,
                ];
            }
        }

        foreach (array_chunk($cities, 100) as $chunk) {
            DB::table('cities')->insert($chunk);
        }
    }
}